### PR TITLE
Add a python example for reading data from GC

### PR DESCRIPTION
**Pull request by ijnek**
This is an additional file that is useful for teams using python to write their gamecontroller client for the robot.
@ahasselbring Could we discuss if this is worth adding to the repo?

I have marked it as a draft as I have only done some preliminary testing yet, but so far the example in the docstring works.

---

EDIT:

I have performed manual testing and can confirm all fields seem to be working correctly.

### CODE REVIEW

**Comment by ahasselbring** [comment]
Thanks, I like this (and I am willing to keep it in sync with the other parts). Maybe it's worth to rename the directory to something else than `include/`. I sometimes use the following script for testing the GameController, which, if adapted and extended, would also benefit and could serve as example.

```python
#!/usr/bin/env python3

import argparse
import socket
import struct
import sys

parser = argparse.ArgumentParser(description='Send aliveness messages to the GameController.')
parser.add_argument('players', metavar='N', type=int, nargs='+', help='The player numbers of the alive robots.')
parser.add_argument('--team', dest='team', type=int, default=5, help='The team number of the alive robots.')
args = parser.parse_args()

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

def send_rgrt_message(sock, dst, player, team, fallen):
    sock.sendto(struct.pack('BBBBBBBBffffff', ord('R'), ord('G'), ord('r'), ord('t'), 4, player, team, 1 if fallen else 0, 0, 0, 0, 0, 0, 0), (dst, 3939))

for player in args.players:
    send_rgrt_message(sock, '192.168.0.196', player, args.team, False)
```

**Comment by ijnek** [comment]
Great, I'll work towards structuring it in the way you want it.

What do you think of putting both these python files and the existing h files in a parent ``examples`` directory?
    
    |-- deps/
    |-- examples/
    |   |-- python/
    |   |   |-- robocup_game_control_data.py
    |   |   |-- robocup_game_control_return_data.py
    |   |   |-- spl_standard_message.py
    |   |-- c/
    |   |   |-- RoboCupGameControlData.h
    |   |   |-- SPLStandardMessage.h
    |-- resources/
    |-- src/
    
Adapting the ``send_rgrt_message`` method in the script from your previous message, you'd have something like:

```python
from construct import Container
from robocup_game_control_return_data import RoboCupGameControlReturnData

def send_rgrt_message(sock, dst, player, team, fallen):
    container = Container(teamNum=team, playerNum=player, fallen=(1 if fallen else 0))
    data = RoboCupGameControlReturnData.build(container)
    sock.sendto(data, (dst, 3939))
```

We could add that to a ``scripts/`` or ``utils/`` dir somewhere outside the ``examples`` directory?

**Comment by ijnek** [comment]
Also considering the fast-approaching perhaps-EOL of this GC, I can just add it to a subdirectory called python.

**Comment by jayenashar** [comment]
> Also considering the fast-approaching perhaps-EOL of this GC, I can just add it to a subdirectory called python.

i don't know about "fast-approaching".  GORE 2023 will probably be the first test of the new GC.

We could also have a separate repo for the examples?

**Comment by ijnek** [comment]
I don't have a preference on separating the repo or not, I'll leave that up to the maintainers.
If the example repo can be set up soon, I can retarget my PR. Otherwise, I'd prefer merging in the work to this repo with one of my suggested directory structures, and have the maintainer separate out the examples to another repo when they can get around to it.

**Comment by ahasselbring** [comment]
I think it can still be added to this repository and copied later, because it isn't tied to the implementation of the GC. I think the directory structure [here](https://github.com/RoboCup-SPL/GameController/pull/45#issuecomment-1121665579) is fine and the scripts could later go into the examples directory as well.

**Comment by sseering** [comment]
As you are using 3rd party libraries you should also include a `requirements.txt ` which is the standard way for python to declare dependencies.

**Comment by ijnek** [comment]
@ahasselbring This is now ready for review.
@sseering Thanks for the suggestion of the ``requirements.txt``, I've added that in.

**Pull request merged**
